services:
  - type: web
    name: urls-centralizer
    runtime: go
    buildCommand: go build -o main ./cmd
    startCommand: ./main
    envVars:
      - key: PORT
        value: 10000
    autoDeploy: true
